spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  app:
      jwtSecret: mySecretKey1239234@#%$^$!@
      jwtExpirationMs: 99999999999999999999999999999999